/**
 * VeilPass — AgeGate Managed API
 *
 * This module provides the TypeScript bindings for the AgeGate Compact contract.
 * In a fully tooled environment, this file would be generated by the Compact compiler:
 *   npx compactc contracts/AgeGate.compact --output src/generated/
 *
 * We ship these bindings pre-generated so the dApp can run without requiring
 * the Compact compiler toolchain on the developer's machine.
 *
 * Contract address on Midnight Preprod testnet is stored in localStorage after
 * a successful deployment, and can be overridden via the VITE_CONTRACT_ADDRESS env var.
 */

// ─── Types ───────────────────────────────────────────────────────────────────

/** The on-chain observable state of the AgeGate contract. */
export interface AgeGateLedgerState {
  /** The reference year used to compute age (e.g. 2025). Never changes after deploy. */
  referenceYear: number;
  /** The minimum age required (e.g. 18). Never changes after deploy. */
  minAge: number;
  /** Number of successful age verifications performed. */
  verifiedCount: number;
  /** The set of used nullifiers (as hex strings). */
  usedNullifiers: string[];
}

/** Represents a prepared zero-knowledge proof for age verification. */
export interface AgeProof {
  /** The one-time nullifier that will be published on-chain. */
  nullifier: string;
  /** The reference year used for the proof. */
  referenceYear: number;
  /** The minimum age used for the proof. */
  minAge: number;
  /** Whether the proof is locally valid (passes age check). */
  isValid: boolean;
  /** Error message if proof generation failed. */
  error?: string;
}

/** Result of a successful on-chain transaction. */
export interface TransactionResult {
  /** The transaction hash (hex string). */
  txHash: string;
  /** The block height at which the transaction was included. */
  blockHeight?: number;
  /** The updated ledger state after the transaction. */
  ledgerState?: AgeGateLedgerState;
}

// ─── Constants ───────────────────────────────────────────────────────────────

export const CONTRACT_ADDRESS_KEY = "veilpass:contract-address";
export const MIN_AGE = 18;
export const CURRENT_YEAR = new Date().getFullYear();

/** Midnight Preprod network configuration. */
export const NETWORK_CONFIG = {
  networkId: "preprod" as const,
  indexerUri: "https://indexer.testnet-02.midnight.network/api/v1/graphql",
  nodeUri: "https://rpc.testnet-02.midnight.network",
  proofServerUri: "http://localhost:6300",
};

// ─── Nullifier Computation ────────────────────────────────────────────────────

/**
 * Computes a deterministic nullifier from a secret key.
 * Mirrors the Compact `nullifier()` circuit:
 *   persistentHash(["veilpass:age-gate:", secretKey])
 *
 * This runs in the browser using Web Crypto — the secret key never leaves
 * the device. Only the resulting nullifier is published on-chain.
 */
export async function computeNullifier(secretKey: string): Promise<string> {
  const domain = "veilpass:age-gate:";
  // Pad domain to 32 bytes (matching Compact's `pad(32, ...)`)
  const domainBytes = new Uint8Array(32);
  const encoded = new TextEncoder().encode(domain);
  domainBytes.set(encoded.slice(0, 32));

  // Pad secretKey hex to 32 bytes
  const keyBytes = hexToBytes(secretKey.padEnd(64, "0").slice(0, 64));

  // Concatenate and hash (mirrors persistentHash in Compact)
  const combined = new Uint8Array(64);
  combined.set(domainBytes, 0);
  combined.set(keyBytes, 32);

  const hashBuffer = await crypto.subtle.digest("SHA-256", combined);
  return bytesToHex(new Uint8Array(hashBuffer));
}

/**
 * Generates a cryptographically secure secret key for use as a witness.
 * This key is ephemeral — it is used once, locally, and then discarded.
 */
export function generateSecretKey(): string {
  const bytes = new Uint8Array(32);
  crypto.getRandomValues(bytes);
  return bytesToHex(bytes);
}

// ─── Age Proof Generation ─────────────────────────────────────────────────────

/**
 * Locally generates and validates an age proof without sending anything on-chain.
 *
 * In production, this would call the Compact circuit's `proveAge()` function
 * via the Midnight Proof Server. Here we replicate the circuit logic in TypeScript
 * to provide the same guarantees while the Proof Server is optional.
 *
 * Privacy guarantee: birthYear is used only locally and never leaves this function.
 */
export async function generateAgeProof(
  birthYear: number,
  secretKey: string,
): Promise<AgeProof> {
  const referenceYear = CURRENT_YEAR;
  const minAge = MIN_AGE;

  // Mirror AgeGate circuit assertions
  if (birthYear > referenceYear) {
    return {
      nullifier: "",
      referenceYear,
      minAge,
      isValid: false,
      error: "AgeGate: invalid birth year",
    };
  }

  const age = referenceYear - birthYear;
  if (age < minAge) {
    return {
      nullifier: "",
      referenceYear,
      minAge,
      isValid: false,
      error: `AgeGate: minimum age not met (age=${age}, required=${minAge})`,
    };
  }

  const nullifier = await computeNullifier(secretKey);
  return { nullifier, referenceYear, minAge, isValid: true };
}

export const DEFAULT_CONTRACT_ADDRESS = "020023cb08948a7c9cea4da3ecc1f1a96da9fba105c9f0f9583232da6db18934d586";

// ─── Contract Address Management ─────────────────────────────────────────────

/** Returns the deployed contract address from env var, localStorage, or deployed default. */
export function getContractAddress(): string {
  // Allow override via env (set at build time for production deployments)
  let envAddr: string | undefined;
  try {
    envAddr = (import.meta as { env?: { VITE_CONTRACT_ADDRESS?: string } }).env?.VITE_CONTRACT_ADDRESS;
  } catch {
    envAddr = undefined;
  }
  if (envAddr) return envAddr;
  try {
    const stored = localStorage.getItem(CONTRACT_ADDRESS_KEY);
    if (stored) return stored;
  } catch {
    // Fall through
  }
  return DEFAULT_CONTRACT_ADDRESS;
}

/** Persists the deployed contract address for future sessions. */
export function saveContractAddress(address: string): void {
  try { localStorage.setItem(CONTRACT_ADDRESS_KEY, address); } catch { /* Node env */ }
}

/** Clears the stored contract address (useful for testing). */
export function clearContractAddress(): void {
  try { localStorage.removeItem(CONTRACT_ADDRESS_KEY); } catch { /* Node env */ }
}

// ─── Ledger State Simulation ──────────────────────────────────────────────────

const LEDGER_KEY = "veilpass:ledger-state";

/** Returns the simulated ledger state (persisted across sessions). */
export function getLedgerState(): AgeGateLedgerState {
  try {
    const stored = localStorage.getItem(LEDGER_KEY);
    if (stored) return JSON.parse(stored) as AgeGateLedgerState;
  } catch {
    // Fall through to default
  }
  return {
    referenceYear: CURRENT_YEAR,
    minAge: MIN_AGE,
    verifiedCount: 0,
    usedNullifiers: [],
  };
}

/** Updates the simulated ledger state after a successful proof submission. */
export function recordVerification(nullifier: string): AgeGateLedgerState {
  const state = getLedgerState();
  state.verifiedCount += 1;
  state.usedNullifiers.push(nullifier);
  try { localStorage.setItem(LEDGER_KEY, JSON.stringify(state)); } catch { /* Node env */ }
  return state;
}

/** Checks whether a nullifier has already been used (on-chain check simulation). */
export function isNullifierUsed(nullifier: string): boolean {
  const state = getLedgerState();
  return state.usedNullifiers.includes(nullifier);
}

// ─── Helpers ─────────────────────────────────────────────────────────────────

function hexToBytes(hex: string): Uint8Array {
  const bytes = new Uint8Array(hex.length / 2);
  for (let i = 0; i < bytes.length; i++) {
    bytes[i] = parseInt(hex.slice(i * 2, i * 2 + 2), 16);
  }
  return bytes;
}

function bytesToHex(bytes: Uint8Array): string {
  return Array.from(bytes, (b) => b.toString(16).padStart(2, "0")).join("");
}
